CREATE WAREHOUSE ECHOMIND_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE DATABASE ECHOMIND_DB;
CREATE SCHEMA ECHOMIND_DB.APP;
CREATE STAGE ECHOMIND_DB.APP.AUDIO_STAGE ENCRYPTION=(TYPE='SNOWFLAKE_SSE') DIRECTORY=(ENABLE=TRUE);

CREATE TABLE ECHOMIND_DB.APP.CALL_SEGMENTS (
    CALL_ID VARCHAR,
    SEGMENT_ID INT,
    SPEAKER VARCHAR,
    START_TIME FLOAT,
    END_TIME FLOAT,
    SEGMENT_TEXT VARCHAR,
    SENTIMENT FLOAT,
    EMBEDDING VECTOR(FLOAT, 1024),
    CLUSTER_ID INT,
    PCA_X FLOAT,
    PCA_Y FLOAT,
    TOPIC_LABEL VARCHAR
);

CREATE TABLE ECHOMIND_DB.APP.CALL_INSIGHTS (
    CALL_ID VARCHAR,
    OBJECTIONS VARCHAR,
    COMPETITOR_MENTIONS VARCHAR,
    BUYING_SIGNALS VARCHAR,
    PRICING_DISCUSSIONS VARCHAR,
    ACTION_ITEMS VARCHAR,
    NEXT_STEPS VARCHAR,
    LEAD_INTENT_SCORE INT
);
